MCU: stm32f4xx
PllConfig:
  PllSource: HSE
  HseFrequency: 8000000
  HsiFrequency: 16000000
  RequireFrequency: 180000000
  
  TemplatePath: ./targets/stm32/stm32_target_pll/pll.template
  DestinationPath: ./pll.h